replicaCount: 2
image:
  repository: nginx
  tag: 1.27.4
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: nginx.local
      paths:
        - path: /
          pathType: ImplementationSpecific
resources: {}

affinity: {}
nodeSelector: {}
tolerations: []